import json

new_meds = [
    {"nome": "Ácido Acetilsalicílico 100mg", "classificacao": "ANALGÉSICOS E ANTIPIRÉTICOS", "posologia": "1 cp/dia (antiagregante plaquetário)", "indicacao": "", "status": "Disponível"},
    {"nome": "Dipirona 500mg cp", "classificacao": "ANALGÉSICOS E ANTIPIRÉTICOS", "posologia": "500-1000mg a cada 6-8h (máx. 4g/dia)", "indicacao": "", "status": "Disponível"},
    {"nome": "Dipirona 500mg/mL gotas", "classificacao": "ANALGÉSICOS E ANTIPIRÉTICOS", "posologia": "20-40 gotas a cada 6-8h (adultos)", "indicacao": "", "status": "Disponível"},
    {"nome": "Paracetamol 500mg", "classificacao": "ANALGÉSICOS E ANTIPIRÉTICOS", "posologia": "500-1000mg a cada 6-8h (máx. 4g/dia)", "indicacao": "", "status": "Disponível"},
    {"nome": "Paracetamol 750mg", "classificacao": "ANALGÉSICOS E ANTIPIRÉTICOS", "posologia": "750mg a cada 6-8h (máx. 4g/dia)", "indicacao": "", "status": "Disponível"},
    {"nome": "Paracetamol gotas", "classificacao": "ANALGÉSICOS E ANTIPIRÉTICOS", "posologia": "40mg/kg/dia dividido a cada 6h (crianças)", "indicacao": "", "status": "Disponível"},
    {"nome": "Ibuprofeno 600mg", "classificacao": "ANTI-INFLAMATÓRIOS NÃO ESTEROIDAIS (AINEs)", "posologia": "400-600mg a cada 6-8h, com alimento", "indicacao": "", "status": "Disponível"},
    {"nome": "Ibuprofeno gotas", "classificacao": "ANTI-INFLAMATÓRIOS NÃO ESTEROIDAIS (AINEs)", "posologia": "5-10mg/kg/dose a cada 6-8h (crianças)", "indicacao": "", "status": "Disponível"},
    {"nome": "Nimesulida 100mg", "classificacao": "ANTI-INFLAMATÓRIOS NÃO ESTEROIDAIS (AINEs)", "posologia": "100mg a cada 12h, com alimento (adultos)", "indicacao": "", "status": "Disponível"},
    {"nome": "Captopril 25mg", "classificacao": "ANTI-HIPERTENSIVOS — IECA (Inibidores da ECA)", "posologia": "25-50mg a cada 8-12h", "indicacao": "", "status": "Disponível"},
    {"nome": "Enalapril Maleato 5mg", "classificacao": "ANTI-HIPERTENSIVOS — IECA (Inibidores da ECA)", "posologia": "5-40mg/dia em 1-2 doses", "indicacao": "", "status": "Disponível"},
    {"nome": "Enalapril Maleato 10mg", "classificacao": "ANTI-HIPERTENSIVOS — IECA (Inibidores da ECA)", "posologia": "10-40mg/dia em 1-2 doses", "indicacao": "", "status": "Disponível"},
    {"nome": "Enalapril Maleato 20mg", "classificacao": "ANTI-HIPERTENSIVOS — IECA (Inibidores da ECA)", "posologia": "20-40mg/dia em 1-2 doses", "indicacao": "", "status": "Disponível"},
    {"nome": "Losartana Potássica 50mg", "classificacao": "ANTI-HIPERTENSIVOS — BRA (Bloqueadores do Receptor de Angiotensina)", "posologia": "50-100mg/dia em 1-2 doses", "indicacao": "", "status": "Disponível"},
    {"nome": "Besilato de Anlodipino 5mg", "classificacao": "ANTI-HIPERTENSIVOS — Bloqueadores dos Canais de Cálcio", "posologia": "5-10mg/dia, 1x/dia", "indicacao": "", "status": "Disponível"},
    {"nome": "Cloridrato de Verapamil 80mg", "classificacao": "ANTI-HIPERTENSIVOS — Bloqueadores dos Canais de Cálcio", "posologia": "80-120mg a cada 8h", "indicacao": "", "status": "Disponível"},
    {"nome": "Atenolol 50mg", "classificacao": "ANTI-HIPERTENSIVOS — Betabloqueadores", "posologia": "25-100mg/dia, 1x/dia", "indicacao": "", "status": "Disponível"},
    {"nome": "Carvedilol 3,125mg", "classificacao": "ANTI-HIPERTENSIVOS — Betabloqueadores", "posologia": "3,125-25mg a cada 12h (iniciar com dose baixa)", "indicacao": "", "status": "Disponível"},
    {"nome": "Carvedilol 6,25mg", "classificacao": "ANTI-HIPERTENSIVOS — Betabloqueadores", "posologia": "6,25-25mg a cada 12h", "indicacao": "", "status": "Disponível"},
    {"nome": "Carvedilol 12,5mg", "classificacao": "ANTI-HIPERTENSIVOS — Betabloqueadores", "posologia": "12,5-25mg a cada 12h", "indicacao": "", "status": "Disponível"},
    {"nome": "Carvedilol 25mg", "classificacao": "ANTI-HIPERTENSIVOS — Betabloqueadores", "posologia": "25mg a cada 12h", "indicacao": "", "status": "Disponível"},
    {"nome": "Propranolol 40mg", "classificacao": "ANTI-HIPERTENSIVOS — Betabloqueadores", "posologia": "40-160mg/dia em 2-3 doses", "indicacao": "", "status": "Disponível"},
    {"nome": "Succinato de Metoprolol 25mg", "classificacao": "ANTI-HIPERTENSIVOS — Betabloqueadores", "posologia": "25-200mg/dia, 1x/dia", "indicacao": "", "status": "Disponível"},
    {"nome": "Succinato de Metoprolol 50mg", "classificacao": "ANTI-HIPERTENSIVOS — Betabloqueadores", "posologia": "50-200mg/dia, 1x/dia", "indicacao": "", "status": "Disponível"},
    {"nome": "Succinato de Metoprolol 100mg", "classificacao": "ANTI-HIPERTENSIVOS — Betabloqueadores", "posologia": "100-200mg/dia, 1x/dia", "indicacao": "", "status": "Disponível"},
    {"nome": "Hidralazina 25mg", "classificacao": "ANTI-HIPERTENSIVOS — Outros", "posologia": "25-75mg a cada 6-8h", "indicacao": "", "status": "Disponível"},
    {"nome": "Hidralazina 50mg", "classificacao": "ANTI-HIPERTENSIVOS — Outros", "posologia": "50-75mg a cada 6-8h", "indicacao": "", "status": "Disponível"},
    {"nome": "Metildopa 250mg", "classificacao": "ANTI-HIPERTENSIVOS — Outros", "posologia": "250-500mg a cada 8h (uso na gestação)", "indicacao": "", "status": "Disponível"},
    {"nome": "Doxazosina Mesilato 2mg", "classificacao": "ANTI-HIPERTENSIVOS — Outros", "posologia": "1-16mg/dia, 1x/dia", "indicacao": "", "status": "Disponível"},
    {"nome": "Doxazosina Mesilato 4mg", "classificacao": "ANTI-HIPERTENSIVOS — Outros", "posologia": "4-16mg/dia, 1x/dia", "indicacao": "", "status": "Disponível"},
    {"nome": "Hidroclorotiazida 25mg", "classificacao": "DIURÉTICOS", "posologia": "12,5-50mg/dia, 1x/dia (manhã)", "indicacao": "", "status": "Disponível"},
    {"nome": "Furosemida 40mg", "classificacao": "DIURÉTICOS", "posologia": "20-80mg/dia, 1-2x/dia", "indicacao": "", "status": "Disponível"},
    {"nome": "Espironolactona 25mg", "classificacao": "DIURÉTICOS", "posologia": "25-100mg/dia, 1x/dia", "indicacao": "", "status": "Disponível"},
    {"nome": "Espironolactona 100mg", "classificacao": "DIURÉTICOS", "posologia": "50-200mg/dia em 1-2 doses", "indicacao": "", "status": "Disponível"},
    {"nome": "Cloridrato de Metformina 500mg", "classificacao": "ANTIDIABÉTICOS", "posologia": "500-2550mg/dia em 2-3 doses, com refeição", "indicacao": "", "status": "Disponível"},
    {"nome": "Cloridrato de Metformina 850mg", "classificacao": "ANTIDIABÉTICOS", "posologia": "850-2550mg/dia em 2-3 doses, com refeição", "indicacao": "", "status": "Disponível"},
    {"nome": "Glibenclamida 5mg", "classificacao": "ANTIDIABÉTICOS", "posologia": "2,5-20mg/dia em 1-2 doses, antes das refeições", "indicacao": "", "status": "Disponível"},
    {"nome": "Glicazida 30mg", "classificacao": "ANTIDIABÉTICOS", "posologia": "30-120mg/dia, 1x/dia (manhã)", "indicacao": "", "status": "Disponível"},
    {"nome": "Glicazida 60mg", "classificacao": "ANTIDIABÉTICOS", "posologia": "60-120mg/dia, 1x/dia (manhã)", "indicacao": "", "status": "Disponível"},
    {"nome": "Sinvastatina 10mg", "classificacao": "HIPOLIPEMIANTES (Estatinas)", "posologia": "10-40mg/dia, 1x/dia (noite)", "indicacao": "", "status": "Disponível"},
    {"nome": "Sinvastatina 20mg", "classificacao": "HIPOLIPEMIANTES (Estatinas)", "posologia": "20-40mg/dia, 1x/dia (noite)", "indicacao": "", "status": "Disponível"},
    {"nome": "Sinvastatina 40mg", "classificacao": "HIPOLIPEMIANTES (Estatinas)", "posologia": "40mg/dia, 1x/dia (noite)", "indicacao": "", "status": "Disponível"},
    {"nome": "Rivaroxabana 5mg", "classificacao": "ANTICOAGULANTES E ANTIAGREGANTES", "posologia": "5-20mg/dia conforme indicação (FA, TVP, EP)", "indicacao": "", "status": "Disponível"},
    {"nome": "Rivaroxabana 10mg", "classificacao": "ANTICOAGULANTES E ANTIAGREGANTES", "posologia": "10mg/dia (profilaxia TVP) ou conforme indicação", "indicacao": "", "status": "Disponível"},
    {"nome": "Rivaroxabana 20mg", "classificacao": "ANTICOAGULANTES E ANTIAGREGANTES", "posologia": "20mg/dia, 1x/dia (com jantar) - FA/TEV", "indicacao": "", "status": "Disponível"},
    {"nome": "Varfarina 5mg", "classificacao": "ANTICOAGULANTES E ANTIAGREGANTES", "posologia": "Dose individualizada; manter INR 2-3 (uso geral)", "indicacao": "", "status": "Disponível"},
    {"nome": "Amiodarona 200mg", "classificacao": "ANTIARRÍTMICOS E CARDIOTÔNICOS", "posologia": "200-400mg/dia (manutenção), ataque: 600-800mg/dia por 1-3 sem.", "indicacao": "", "status": "Disponível"},
    {"nome": "Digoxina 0,25mg", "classificacao": "ANTIARRÍTMICOS E CARDIOTÔNICOS", "posologia": "0,125-0,25mg/dia; dosar nível sérico", "indicacao": "", "status": "Disponível"},
    {"nome": "Propafenona 150mg", "classificacao": "ANTIARRÍTMICOS E CARDIOTÔNICOS", "posologia": "150mg a cada 8h (dose inicial); ajustar conforme resposta", "indicacao": "", "status": "Disponível"},
    {"nome": "Propafenona 300mg", "classificacao": "ANTIARRÍTMICOS E CARDIOTÔNICOS", "posologia": "150-300mg a cada 8h", "indicacao": "", "status": "Disponível"},
    {"nome": "Isossorbida 20mg", "classificacao": "ANTIARRÍTMICOS E CARDIOTÔNICOS", "posologia": "20-40mg a cada 6-8h (excluir 6-8h/dia sem nitrato)", "indicacao": "", "status": "Disponível"},
    {"nome": "Isossorbida 40mg", "classificacao": "ANTIARRÍTMICOS E CARDIOTÔNICOS", "posologia": "40mg a cada 6-8h (excluir período sem nitrato)", "indicacao": "", "status": "Disponível"},
    {"nome": "Salbutamol 100mcg (inalador)", "classificacao": "BRONCODILATADORES E ANTIASMÁTICOS", "posologia": "1-2 jatos a cada 4-6h (resgate); espaçador recomendado", "indicacao": "", "status": "Disponível"},
    {"nome": "Brometo de Ipratrópio 0,25mg/mL", "classificacao": "BRONCODILATADORES E ANTIASMÁTICOS", "posologia": "Nebulização: 250-500mcg a cada 6-8h", "indicacao": "", "status": "Disponível"},
    {"nome": "Beclometasona 50mcg/dose", "classificacao": "BRONCODILATADORES E ANTIASMÁTICOS", "posologia": "100-400mcg/dia em 2-4 inalações (manutenção leve)", "indicacao": "", "status": "Disponível"},
    {"nome": "Beclometasona 250mcg/dose", "classificacao": "BRONCODILATADORES E ANTIASMÁTICOS", "posologia": "500-1000mcg/dia em 2 inalações (manutenção moderada-grave)", "indicacao": "", "status": "Disponível"},
    {"nome": "Budesonida 32mcg", "classificacao": "BRONCODILATADORES E ANTIASMÁTICOS", "posologia": "64-256mcg/dia em 1-2 inalações nasais (rinite)", "indicacao": "", "status": "Disponível"},
    {"nome": "Budesonida 50mcg", "classificacao": "BRONCODILATADORES E ANTIASMÁTICOS", "posologia": "100-400mcg/dia em 1-2 inalações (manutenção asma/DPOC)", "indicacao": "", "status": "Disponível"},
    {"nome": "Acebrofilina 50mg/5mL", "classificacao": "BRONCODILATADORES E ANTIASMÁTICOS", "posologia": "5mL 2-3x/dia (adultos e crianças > 12 anos); mucolítico broncodilatador", "indicacao": "", "status": "Disponível"},
    {"nome": "Dexametasona 0,1mg/g creme", "classificacao": "CORTICOSTEROIDES", "posologia": "Aplicar fina camada 1-3x/dia (uso tópico)", "indicacao": "", "status": "Disponível"},
    {"nome": "Dexametasona 0,5mg/mL (solução)", "classificacao": "CORTICOSTEROIDES", "posologia": "0,5-9mg/dia em 2-4 doses (sistêmico)", "indicacao": "", "status": "Disponível"},
    {"nome": "Hidrocortisona creme", "classificacao": "CORTICOSTEROIDES", "posologia": "Aplicar 1-3x/dia em área afetada", "indicacao": "", "status": "Disponível"},
    {"nome": "Prednisolona 1mg/mL", "classificacao": "CORTICOSTEROIDES", "posologia": "1-2mg/kg/dia (crianças); usar pela manhã", "indicacao": "", "status": "Disponível"},
    {"nome": "Prednisolona 3mg/mL", "classificacao": "CORTICOSTEROIDES", "posologia": "1-2mg/kg/dia (crianças); usar pela manhã", "indicacao": "", "status": "Disponível"},
    {"nome": "Prednisona 5mg", "classificacao": "CORTICOSTEROIDES", "posologia": "5-60mg/dia conforme indicação; manhã com alimento", "indicacao": "", "status": "Disponível"},
    {"nome": "Prednisona 20mg", "classificacao": "CORTICOSTEROIDES", "posologia": "20-60mg/dia conforme indicação, manhã com alimento", "indicacao": "", "status": "Disponível"},
    {"nome": "Omeprazol 20mg", "classificacao": "ANTIÚLCERA / PROTETORES GÁSTRICOS", "posologia": "20-40mg/dia, 30 min antes do café da manhã", "indicacao": "", "status": "Disponível"},
    {"nome": "Hidróxido de Alumínio", "classificacao": "ANTIÚLCERA / PROTETORES GÁSTRICOS", "posologia": "5-10mL ou 1-2 cp a cada 4-6h, entre refeições", "indicacao": "", "status": "Disponível"},
    {"nome": "Lactulose xarope 667mg/mL", "classificacao": "LAXANTES E REGULADORES INTESTINAIS", "posologia": "15-30mL/dia em 1-2 doses (adultos); ajustar", "indicacao": "", "status": "Disponível"},
    {"nome": "Óleo Mineral", "classificacao": "LAXANTES E REGULADORES INTESTINAIS", "posologia": "15-45mL/dia; não usar em deitados ou crianças < 6 anos", "indicacao": "", "status": "Disponível"},
    {"nome": "Dexclorfeniramina 2mg", "classificacao": "ANTI-HISTAMÍNICOS", "posologia": "2mg a cada 4-6h (máx. 12mg/dia); causa sedação", "indicacao": "", "status": "Disponível"},
    {"nome": "Dexclorfeniramina 0,4mg/mL", "classificacao": "ANTI-HISTAMÍNICOS", "posologia": "2mg a cada 6-8h (adultos); 0,15mg/kg/dose (crianças)", "indicacao": "", "status": "Disponível"},
    {"nome": "Desloratadina 0,5mg/mL", "classificacao": "ANTI-HISTAMÍNICOS", "posologia": "10mL/dia (adultos e > 12 anos); 5mL/dia (6-11 anos); não sedativo", "indicacao": "", "status": "Disponível"},
    {"nome": "Loratadina 10mg", "classificacao": "ANTI-HISTAMÍNICOS", "posologia": "10mg/dia, 1x/dia (não sedativo)", "indicacao": "", "status": "Disponível"},
    {"nome": "Loratadina 1mg/mL xarope", "classificacao": "ANTI-HISTAMÍNICOS", "posologia": "10mg/dia (adultos); 5mg/dia < 30kg (crianças)", "indicacao": "", "status": "Disponível"},
    {"nome": "Prometazina 25mg", "classificacao": "ANTI-HISTAMÍNICOS", "posologia": "12,5-25mg a cada 8-12h; causa sedação intensa", "indicacao": "", "status": "Disponível"},
    {"nome": "Brometo de Escopolamina 10mg", "classificacao": "ANTIESPASMÓDICOS / ANTICOLINÉRGICOS", "posologia": "10-20mg a cada 6-8h (espasmos GI/geniturinários)", "indicacao": "", "status": "Disponível"},
    {"nome": "Metoclopramida 10mg", "classificacao": "ANTIEMÉTICOS", "posologia": "10mg a cada 6-8h, 30 min antes das refeições", "indicacao": "", "status": "Disponível"},
    {"nome": "Ondansetrona 8mg", "classificacao": "ANTIEMÉTICOS", "posologia": "8mg a cada 8-12h; 30 min antes da quimioterapia ou conforme náusea", "indicacao": "", "status": "Disponível"},
    {"nome": "Alopurinol 100mg", "classificacao": "ANTI-GOTOSOS", "posologia": "100-600mg/dia; iniciar com 100mg, ajustar conforme uricemia", "indicacao": "", "status": "Disponível"},
    {"nome": "Alopurinol 300mg", "classificacao": "ANTI-GOTOSOS", "posologia": "300mg/dia (dose usual de manutenção); 1x/dia ou dividido", "indicacao": "", "status": "Disponível"},
    {"nome": "Levotiroxina 25mcg", "classificacao": "HORMÔNIOS TIREOIDIANOS", "posologia": "25mcg/dia (dose inicial em idosos/cardiopatas), em jejum", "indicacao": "", "status": "Disponível"},
    {"nome": "Levotiroxina 50mcg", "classificacao": "HORMÔNIOS TIREOIDIANOS", "posologia": "50mcg/dia; ajustar a cada 6-8 semanas pelo TSH", "indicacao": "", "status": "Disponível"},
    {"nome": "Levotiroxina 75mcg", "classificacao": "HORMÔNIOS TIREOIDIANOS", "posologia": "75mcg/dia; ajustar conforme TSH", "indicacao": "", "status": "Disponível"},
    {"nome": "Levotiroxina 100mcg", "classificacao": "HORMÔNIOS TIREOIDIANOS", "posologia": "100mcg/dia; ajustar conforme TSH", "indicacao": "", "status": "Disponível"},
    {"nome": "Alendronato de Sódio 70mg", "classificacao": "BIFOSFONATOS E SUPLEMENTOS ÓSSEOS", "posologia": "70mg 1x/semana, em jejum, com copo cheio d'água; manter-se ereto 30 min", "indicacao": "", "status": "Disponível"},
    {"nome": "Carbonato de Cálcio 500mg + Vitamina D 200UI", "classificacao": "BIFOSFONATOS E SUPLEMENTOS ÓSSEOS", "posologia": "1-2 cp/dia, com refeição", "indicacao": "", "status": "Disponível"},
    {"nome": "Colecalciferol 7.000UI", "classificacao": "BIFOSFONATOS E SUPLEMENTOS ÓSSEOS", "posologia": "7.000UI/semana (manutenção/reposição leve)", "indicacao": "", "status": "Disponível"},
    {"nome": "Colecalciferol 50.000UI", "classificacao": "BIFOSFONATOS E SUPLEMENTOS ÓSSEOS", "posologia": "50.000UI/semana por 8-12 semanas (reposição de deficiência)", "indicacao": "", "status": "Disponível"},
    {"nome": "Levodopa + Benserazida 200+50mg", "classificacao": "ANTIPARKINSONIANOS", "posologia": "1 cp a cada 4-6h; ajustar; tomar 30 min antes das refeições", "indicacao": "", "status": "Disponível"},
    {"nome": "Levodopa + Carbidopa 250+25mg", "classificacao": "ANTIPARKINSONIANOS", "posologia": "1 cp a cada 6-8h; ajustar conforme resposta", "indicacao": "", "status": "Disponível"},
    {"nome": "Ácido Fólico 5mg", "classificacao": "SUPLEMENTOS / VITAMINAS / MINERAIS", "posologia": "5mg/dia (gestantes de risco, anemia megaloblástica)", "indicacao": "", "status": "Disponível"},
    {"nome": "Complexo B", "classificacao": "SUPLEMENTOS / VITAMINAS / MINERAIS", "posologia": "1 cp/dia ou conforme produto", "indicacao": "", "status": "Disponível"},
    {"nome": "Ferropolimaltose 100mg", "classificacao": "SUPLEMENTOS / VITAMINAS / MINERAIS", "posologia": "1 cp/dia (reposição de ferro; melhor tolerância GI que sulfato ferroso)", "indicacao": "", "status": "Disponível"},
    {"nome": "Sulfato Ferroso 40mg", "classificacao": "SUPLEMENTOS / VITAMINAS / MINERAIS", "posologia": "200mg de sulfato ferroso (40mg Fe elementar) 2-3x/dia em jejum", "indicacao": "", "status": "Disponível"},
    {"nome": "Sulfato Ferroso gotas", "classificacao": "SUPLEMENTOS / VITAMINAS / MINERAIS", "posologia": "5mg Fe elementar/kg/dia em 3 doses (crianças)", "indicacao": "", "status": "Disponível"},
    {"nome": "Sais para Reidratação Oral", "classificacao": "SUPLEMENTOS / VITAMINAS / MINERAIS", "posologia": "200-400mL por evacuação líquida (adultos); 50-100mL/kg em 4h (crianças)", "indicacao": "", "status": "Disponível"},
    {"nome": "Aciclovir 200mg", "classificacao": "ANTIVIRAIS", "posologia": "200mg 5x/dia por 5-10 dias (herpes simples/zóster)", "indicacao": "", "status": "Disponível"},
    {"nome": "Aciclovir creme 50mg/g", "classificacao": "ANTIVIRAIS", "posologia": "Aplicar 5x/dia por 4-5 dias (herpes labial)", "indicacao": "", "status": "Disponível"},
    {"nome": "Amoxicilina 500mg", "classificacao": "ANTIBIÓTICOS — Penicilinas", "posologia": "500mg a cada 8h ou 875mg a cada 12h por 7-10 dias", "indicacao": "", "status": "Disponível"},
    {"nome": "Amoxicilina 250mg/5mL", "classificacao": "ANTIBIÓTICOS — Penicilinas", "posologia": "25-50mg/kg/dia dividido a cada 8h (crianças)", "indicacao": "", "status": "Disponível"},
    {"nome": "Amoxicilina + Clavulanato 500+125mg", "classificacao": "ANTIBIÓTICOS — Penicilinas", "posologia": "1 cp a cada 8h ou 12h (7-10 dias); com alimento", "indicacao": "", "status": "Disponível"},
    {"nome": "Amoxicilina + Clavulanato 250mg+5mL", "classificacao": "ANTIBIÓTICOS — Penicilinas", "posologia": "25-45mg/kg/dia dividido a cada 8-12h (crianças)", "indicacao": "", "status": "Disponível"},
    {"nome": "Benzilpenicilina 1.200.000UI (Benzatina)", "classificacao": "ANTIBIÓTICOS — Penicilinas", "posologia": "1.200.000UI IM dose única (faringite estrepto grupo A / sífilis primária)", "indicacao": "", "status": "Disponível"},
    {"nome": "Benzilpenicilina 600.000UI", "classificacao": "ANTIBIÓTICOS — Penicilinas", "posologia": "600.000UI IM (crianças < 27kg); dose única", "indicacao": "", "status": "Disponível"},
    {"nome": "Cefalexina 500mg cp", "classificacao": "ANTIBIÓTICOS — Cefalosporinas", "posologia": "500mg a cada 6h por 7-10 dias", "indicacao": "", "status": "Disponível"},
    {"nome": "Cefalexina 50mg/mL", "classificacao": "ANTIBIÓTICOS — Cefalosporinas", "posologia": "25-50mg/kg/dia dividido a cada 6h (crianças)", "indicacao": "", "status": "Disponível"},
    {"nome": "Azitromicina 500mg", "classificacao": "ANTIBIÓTICOS — Macrolídeos", "posologia": "500mg/dia por 3-5 dias (dose única diária)", "indicacao": "", "status": "Disponível"},
    {"nome": "Azitromicina 200mg/5mL", "classificacao": "ANTIBIÓTICOS — Macrolídeos", "posologia": "10mg/kg/dia por 3-5 dias (crianças)", "indicacao": "", "status": "Disponível"},
    {"nome": "Claritromicina 250mg/5mL", "classificacao": "ANTIBIÓTICOS — Macrolídeos", "posologia": "7,5mg/kg a cada 12h (crianças, máx. 500mg/dose)", "indicacao": "", "status": "Disponível"},
    {"nome": "Ciprofloxacino 500mg", "classificacao": "ANTIBIÓTICOS — Quinolonas", "posologia": "500mg a cada 12h por 7-14 dias (UTI: 7 dias)", "indicacao": "", "status": "Disponível"},
    {"nome": "Metronidazol 250mg", "classificacao": "ANTIBIÓTICOS / ANTIPROTOZOÁRIOS — Nitroimidazóis", "posologia": "250mg a cada 8h por 7 dias (giardíase, tricomoníase)", "indicacao": "", "status": "Disponível"},
    {"nome": "Metronidazol 400mg", "classificacao": "ANTIBIÓTICOS / ANTIPROTOZOÁRIOS — Nitroimidazóis", "posologia": "400mg a cada 8h (anaeróbios); 2g dose única (tricomoníase)", "indicacao": "", "status": "Disponível"},
    {"nome": "Metronidazol creme vaginal", "classificacao": "ANTIBIÓTICOS / ANTIPROTOZOÁRIOS — Nitroimidazóis", "posologia": "Aplicar 1 aplicador vaginal/noite por 5-7 noites", "indicacao": "", "status": "Disponível"},
    {"nome": "Sulfametoxazol + Trimetoprima 400+80mg", "classificacao": "ANTIBIÓTICOS — Sulfonamidas / Associações", "posologia": "1 cp a cada 12h por 7-14 dias (ITU)", "indicacao": "", "status": "Disponível"},
    {"nome": "Sulfametoxazol + Trimetoprima 200+40/5mL", "classificacao": "ANTIBIÓTICOS — Sulfonamidas / Associações", "posologia": "4-6mg/kg de TMP a cada 12h (crianças)", "indicacao": "", "status": "Disponível"}
]

with open('data/medicamentos.json', 'r', encoding='utf-8') as f:
    existing_meds = json.load(f)

existing_names = {m['nome'] for m in existing_meds}
added = 0

for m in new_meds:
    if m['nome'] not in existing_names:
        existing_meds.append(m)
        added += 1

if added > 0:
    with open('data/medicamentos.json', 'w', encoding='utf-8') as f:
        json.dump(existing_meds, f, indent=2, ensure_ascii=False)
    print(f"Adicionados {added} novos medicamentos ao JSON.")
else:
    print("Nenhum medicamento novo para adicionar.")
